server:
  port: 8000
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                     # 数据源
    platform: h2                  # 数据源类型
    schema: classpath:schema.sql  # 指定建表脚本
    data: classpath:data.sql      # 指定数据脚本
  application:
    name: microservice-provider-user-trace    # 10.3 sleuth
logging:                          # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    org.springframework.web.servlet.DispatcherServlet: DEBUG  # 10.3 sleuth
    org.springframework.cloud.sleuth: DEBUG # 10.3 跟踪请求

## info
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
management:
  security:
    enabled: false
    