server:
  port: 8010

user:
  userServiceUrl: http://localhost:8000/

spring:
  application:
    name: microservice-consumer-movie # 4.5 注册到Eureka Server显示的名称

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true # 注册自己的ip到Eureka,否则是自己的OS-hostname

# 5.1 自定义ribbon配置
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
